version: "3"

services:
    csgo:
        image: romcheg/csgo-dedicated-server:latest
        ports: 
            - "27020:27020/udp"
            - "27015:27015/tcp"
            - "27015:27015/udp"
        # volumes:
        #    - /home/ubuntu/csgo:/home/steam/csgo
        environment:
            # Get a token here:
            # https://steamcommunity.com/dev/managegameservers
            STEAM_ACCOUNT_TOKEN: "changeme"
            STEAM_AUTHKEY: "changeme"
            SRCDS_RCONPW: "changeme"
            SRCDS_PW: "changeme"
