#! /bin/bash

set -eux

STEAM_USER=${STEAM_USER:-"steam"}
STEAM_USER_HOMEDIR=${STEAM_USER_HOMEDIR:="/home/$STEAM_USER"}
STEAM_CMD_DIR=${STEAM_CMD_DIR:-"$STEAM_USER_HOMEDIR/steamcmd"}
CS_GO_DIR=${CS_GO_DIR:-"$STEAM_USER_HOMEDIR/csgo"}
CSGO_UPDATE_SCRIPT=${CSGO_UPDATE_SCRIPT:-"${STEAM_USER_HOMEDIR}/csgo_update.txt"}